
const addProductSchema = {
    body:{
        type:'object',
        required:['name','category','hsncode'],
        properties:{
            name:{
                "type":"string",
                "minLength":1
            },
            category:{
                "type":"string",
                "minLength":1
            },
            hsncode:{
                "type":"string",
                "minLength":1
            },
            company:{
                "type":"string"
            },
            serialNo:{
                "type":"string"
            },
            availableStock:{
                "type":"string"
            }
        }
    }
}
module.exports={
    addProductSchema
}